const BUILD='KZ-ENTERPRISE-V2.2-R8-OPERATIONAL-20260920';
const $=id=>document.getElementById(id);
const ERROR_TEXT={"region is required":"请填写地区","service is required":"请填写服务项目","keyword is required":"请选择或填写主关键词","title is required":"请填写任务内容","至少填写一条可核验的同行或市场观察":"请至少填写一条可核验的市场观察"};
async function api(path,options){const r=await fetch(path,options);let data={};try{data=await r.json()}catch{}if(!r.ok){const raw=data.error||`本地服务返回 ${r.status}`;throw new Error(ERROR_TEXT[raw]||raw)}return data}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function list(id,items,empty){$(id).innerHTML=(items?.length?items:[empty]).map(x=>`<li>${esc(x)}</li>`).join('')}
function tasks(id,data){const items=data?.tasks||[];$(id).className=items.length?'':'friendly-empty';$(id).innerHTML=items.length?items.map(t=>{const auto=t.execution==='autonomous'||t.risk==='non_financial';const label=t.risk==='financial'?'平台人工':auto?'自动执行':'待核对';const detail=t.risk==='financial'?'资金事项只记录，需到平台后台人工处理':auto?'到期后由 R7 自动执行并写入结果':'按当前策略执行';return `<div class="task"><strong>${esc(t.title)}</strong><span class="tag">${esc(label)}</span><p>${esc(t.reason||detail)}</p></div>`}).join(''):'尚未生成明日计划'}
function showReview(r){if(r.status!=='generated')return;$('review-headline').textContent=r.summary.headline;$('review-policy').textContent=r.summary.data_policy;list('problems',r.problems,'今日未发现已验证问题');list('opportunities',r.opportunities,'今日没有足够数据识别机会');tasks('review-plan',r.tomorrow_plan)}
async function loadSummary(){const s=await api('/api/operation-summary/today');$('summary-headline').textContent=s.headline;$('summary-policy').textContent=s.data_policy;const metricNames={orders:'订单',users:'用户',revenue:'收入',masters:'服务师傅',leaders:'团长',promotion:'推广效果'};const entries=Object.entries(s.verified_metrics||{});$('metrics').innerHTML=entries.length?entries.map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><small>${esc(metricNames[k]||k)}</small></div>`).join(''):'<div class="friendly-empty">没有已验证指标</div>';$('missing').textContent=s.missing_metrics?.length?`尚未接入：${s.missing_metrics.map(x=>metricNames[x]||x).join('、')}`:'今日指标已完整接入'}
async function loadPlan(){const p=await api('/api/tomorrow-plan/latest');$('plan-date').textContent=p.date?`${p.date} 明日计划`:'尚未生成';tasks('plan-list',p)}
async function loadHistory(){const h=await api('/api/history');$('history-list').innerHTML=h.items?.length?h.items.map(r=>`<article class="history-card"><div class="meta">${formatTime(r.generated_at)}</div><h3>${esc(r.summary.headline)}</h3><p>${esc(r.problems[0]||'没有已验证问题')}</p></article>`).join(''):'<article class="friendly-empty">还没有历史记录，生成今日复盘后会自动保存在这里。</article>'}
async function loadMemory(){const [m,e]=await Promise.all([api('/api/memory'),api('/api/experiments')]);$('memory-list').innerHTML=m.entries?.length?m.entries.map(x=>`<div class="task"><strong>${esc(x.statement)}</strong><span class="tag">${esc(x.category)}</span><p>${esc(x.evidence||'未附证据')}</p></div>`).join(''):esc(m.message||'尚无学习记录');$('experiment-list').innerHTML=e.experiments?.length?e.experiments.map(x=>`<div class="task"><strong>${esc(x.name)}</strong><p>${esc(x.result||'进行中')}</p></div>`).join(''):'尚无实验记录'}
function formatTime(value){if(!value)return'';try{return new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return value}}
function toast(message,type='ok'){const feedback=$('action-feedback');feedback.textContent=(type==='error'?'需要处理：':'操作结果：')+message;feedback.className=`action-feedback ${type==='error'?'error':'ok'}`;feedback.hidden=false;$('toast').textContent=message;$('toast').className=`show ${type}`;setTimeout(()=>$('toast').className='',2600)}
function openPage(page){const button=document.querySelector(`.nav[data-page="${page}"]`);if(!button)return;document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));button.classList.add('active');$(page).classList.add('active');$('action-feedback').hidden=true;$('page-heading').textContent=button.dataset.title;$('page-subtitle').textContent=button.dataset.subtitle;window.scrollTo({top:0,behavior:'smooth'});if(page==='dashboard'){loadDashboard();if(window.loadControlCenter)loadControlCenter()}if(page==='workflow'){if(window.applyAutonomyCopy)window.applyAutonomyCopy();if(window.loadR7)loadR7()}if(page==='connections'&&window.loadIntegrations)loadIntegrations();if(page==='automation'&&window.loadOperations)loadOperations();if(page==='insights'&&window.loadInsights)loadInsights();if(page==='promotion'&&window.loadPromotion)loadPromotion()}
function bindInteractiveCard(card,handler,label){if(!card||card.dataset.interactionBound==='1')return;card.dataset.interactionBound='1';card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',label);card.title=label;card.style.cursor='pointer';const activate=()=>handler();card.addEventListener('click',activate);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();activate()}})}
function focusAnalyticsImport(message){openPage('analytics');setTimeout(()=>{$('business-json')?.scrollIntoView({behavior:'smooth',block:'center'});toast(message||'真实经营数据尚未接入，请先导入已验证聚合快照')},0)}
function bindSummaryCards(){const stats=[...document.querySelectorAll('#dashboard .stat-grid article')];const statActions=[()=>{openPage('workflow');toast('已打开自动任务与 AI 员工')},()=>{openPage('promotion');toast('已打开内容草稿与生成记录')},()=>{openPage('promotion');toast('已打开关键词与内容增长中心')},()=>{openPage('automation');toast('已打开推广日历')}];const statLabels=['查看自动任务','查看内容草稿','查看研究关键词','查看推广日历'];stats.forEach((card,index)=>bindInteractiveCard(card,statActions[index],statLabels[index]));const reviewCards=[...document.querySelectorAll('#review .grid.three article')];const reviewActions=[()=>{openPage('summary');toast('已打开今日运营总结')},()=>{openPage('insights');toast('已打开市场与客户洞察')},()=>{openPage('plan');toast('已打开明日计划')}];const reviewLabels=['查看今日运营总结','查看问题分析依据','查看增长机会对应计划'];reviewCards.forEach((card,index)=>bindInteractiveCard(card,reviewActions[index],reviewLabels[index]));const analyticsHead=document.querySelector('#analytics .analytics-head');bindInteractiveCard(analyticsHead,()=>{const connected=$('analytics-status')?.textContent.includes('已连接');if(connected)toast('经营数据已连接，当前卡片显示已验证汇总');else focusAnalyticsImport('真实经营数据尚未接入，点击后已定位到导入入口')},'查看经营数据接入状态');const analyticsCards=[...document.querySelectorAll('#analytics .analytics-grid article')];const channelCard=$('channel-effect')?.closest('article');if(channelCard)analyticsCards.push(channelCard);analyticsCards.forEach(card=>bindInteractiveCard(card,()=>{const connected=$('analytics-status')?.textContent.includes('已连接');if(connected)toast('该分析已展示当前已验证经营数据');else focusAnalyticsImport('该分析依赖已验证经营数据；当前未接入，已定位到导入入口')},'查看该经营分析的数据来源'))}
function ensureDashboardHumanPanel(){let panel=$('dash-human-panel');if(panel)return panel;const grids=document.querySelectorAll('#dashboard .dashboard-grid');if(!grids.length)return null;panel=document.createElement('article');panel.id='dash-human-panel';panel.className='wide';panel.innerHTML='<div class="article-head"><div><label>平台人工待处理</label><h3 id="dash-human-title">0 项</h3></div><button class="text-button" id="dash-human-open">查看全部</button></div><div id="dash-human-list" class="friendly-empty">当前没有需要平台人工介入的资金事项。</div>';grids[0].parentNode.insertBefore(panel,grids[0]);panel.querySelector('#dash-human-open').addEventListener('click',()=>{openPage('workflow');setTimeout(()=>document.getElementById('r7-human-panel')?.scrollIntoView({behavior:'smooth',block:'start'}),100)});return panel}
function renderDashboardHuman(items){ensureDashboardHumanPanel();const rows=(items||[]).slice(0,3);$('dash-human-title').textContent=`${(items||[]).length} 项`;$('dash-human-list').className=rows.length?'':'friendly-empty';$('dash-human-list').innerHTML=rows.length?rows.map(x=>`<div class="mini-row"><span class="dot high"></span><strong>${esc(x.title||'资金事项')}</strong><small>${esc(x.status||'待平台人工处理')} · ${formatTime(x.created_at)}</small></div>`).join(''):'当前没有需要平台人工介入的资金事项。'}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));
document.querySelectorAll('.go-page').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.target)));
bindSummaryCards();
async function loadDashboard(){try{const [d,r7,engine]=await Promise.all([api('/api/command-center'),api('/api/r7/jobs'),api('/api/r7/engine')]);const stateNames={awaiting_approval:'历史待处理',human_required:'平台人工',queued:'自动待执行',running:'自动执行中',completed:'已完成',failed:'失败',cancelled:'已取消'};$('dash-pending').textContent=d.task_counts.pending+d.task_counts.in_progress+r7.items.filter(x=>['awaiting_approval','human_required','queued','running','failed'].includes(x.state)).length;$('dash-drafts').textContent=d.draft_count;$('dash-keywords').textContent=d.keyword_count;$('dash-calendar').textContent=d.calendar_days;$('dash-business-message').textContent=d.business_message;const verified=d.business_status==='verified';$('dash-data-badge').textContent=verified?'数据已验证':'等待数据接入';$('dash-data-badge').className=`status-pill ${verified?'ready':'waiting'}`;$('dash-recommendations').innerHTML=d.recommendations.map((x,i)=>`<div class="recommendation"><b>${i+1}</b><span>${esc(x)}</span></div>`).join('');$('dash-tasks').innerHTML=r7.items.length?r7.items.slice(0,5).map(x=>`<div class="mini-row"><span class="dot high"></span><strong>${esc(x.title)}</strong><small>${esc(stateNames[x.state]||'待核对')}</small></div>`).join(''):d.recent_tasks.length?d.recent_tasks.map(x=>`<div class="mini-row"><span class="dot ${esc(x.priority)}"></span><strong>${esc(x.title)}</strong><small>${esc(x.status_label)}</small></div>`).join(''):'<div class="friendly-empty">还没有任务，系统会根据计划自动安排。</div>';$('dash-draft-list').innerHTML=d.recent_drafts.length?d.recent_drafts.map(x=>`<div class="mini-row"><span class="dot draft"></span><strong>${esc(x.kind)}</strong><small>${formatTime(x.created_at)}</small></div>`).join(''):'<div class="friendly-empty">还没有内容草稿，自动计划执行后会在这里出现。</div>';renderDashboardHuman(engine.human_interventions||[])}catch(e){toast(e.message,'error')}}
$('generate').addEventListener('click',async()=>{const b=$('generate');b.disabled=true;b.textContent='正在整理今天的数据…';try{const r=await api('/api/daily-review/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});showReview(r);await Promise.all([loadSummary(),loadPlan(),loadHistory(),loadMemory(),loadDashboard()]);toast('今日复盘已生成并保存')}catch(e){toast(e.message,'error')}finally{b.disabled=false;b.textContent='重新生成今日复盘'}});
$('today-label').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
(async()=>{try{const s=await api('/api/status');if(s.build!==BUILD)throw new Error('前后端构建版本不一致，请重新安装最新版本');document.querySelector('.service').classList.add('ok');$('service-text').textContent='本地服务正常';showReview(await api('/api/daily-review/latest'));await Promise.all([loadSummary(),loadPlan(),loadHistory(),loadMemory(),loadDashboard(),window.loadControlCenter?loadControlCenter():Promise.resolve()]);if(window.applyAutonomyCopy)window.applyAutonomyCopy()}catch(e){$('service-text').textContent=e.message;toast(e.message,'error')}})();
console.log(`KAZUIZHI_BUILD=${BUILD}`);
