const BUILD='KZ-ENTERPRISE-V2-BETA-20260916-R6';
const $=id=>document.getElementById(id);
const ERROR_TEXT={"region is required":"请填写地区","service is required":"请填写服务项目","keyword is required":"请选择或填写主关键词","title is required":"请填写任务内容","至少填写一条可核验的同行或市场观察":"请至少填写一条可核验的市场观察"};
async function api(path,options){const r=await fetch(path,options);let data={};try{data=await r.json()}catch{}if(!r.ok){const raw=data.error||`本地服务返回 ${r.status}`;throw new Error(ERROR_TEXT[raw]||raw)}return data}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function list(id,items,empty){$(id).innerHTML=(items?.length?items:[empty]).map(x=>`<li>${esc(x)}</li>`).join('')}
function tasks(id,data){const items=data?.tasks||[];$(id).className=items.length?'':'friendly-empty';$(id).innerHTML=items.length?items.map(t=>`<div class="task"><strong>${esc(t.title)}</strong><span class="tag">${esc(t.risk==='low'?'低风险建议':t.risk)}</span><p>${esc(t.reason)} · ${esc(t.action)}</p></div>`).join(''):'尚未生成明日计划'}
function showReview(r){if(r.status!=='generated')return;$('review-headline').textContent=r.summary.headline;$('review-policy').textContent=r.summary.data_policy;list('problems',r.problems,'今日未发现已验证问题');list('opportunities',r.opportunities,'今日没有足够数据识别机会');tasks('review-plan',r.tomorrow_plan)}
async function loadSummary(){const s=await api('/api/operation-summary/today');$('summary-headline').textContent=s.headline;$('summary-policy').textContent=s.data_policy;const entries=Object.entries(s.verified_metrics||{});$('metrics').innerHTML=entries.length?entries.map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><small>${esc(k)}</small></div>`).join(''):'<div class="friendly-empty">没有已验证指标</div>';$('missing').textContent=s.missing_metrics?.length?`尚未接入：${s.missing_metrics.join('、')}`:'今日指标已完整接入'}
async function loadPlan(){const p=await api('/api/tomorrow-plan/latest');$('plan-date').textContent=p.date?`${p.date} 明日计划`:'尚未生成';tasks('plan-list',p)}
async function loadHistory(){const h=await api('/api/history');$('history-list').innerHTML=h.items?.length?h.items.map(r=>`<article class="history-card"><div class="meta">${formatTime(r.generated_at)}</div><h3>${esc(r.summary.headline)}</h3><p>${esc(r.problems[0]||'没有已验证问题')}</p></article>`).join(''):'<article class="friendly-empty">还没有历史记录，生成今日复盘后会自动保存在这里。</article>'}
async function loadMemory(){const [m,e]=await Promise.all([api('/api/memory'),api('/api/experiments')]);$('memory-list').innerHTML=m.entries?.length?m.entries.map(x=>`<div class="task"><strong>${esc(x.statement)}</strong><span class="tag">${esc(x.category)}</span><p>${esc(x.evidence||'未附证据')}</p></div>`).join(''):esc(m.message||'尚无学习记录');$('experiment-list').innerHTML=e.experiments?.length?e.experiments.map(x=>`<div class="task"><strong>${esc(x.name)}</strong><p>${esc(x.result||'进行中')}</p></div>`).join(''):'尚无实验记录'}
function formatTime(value){if(!value)return'';try{return new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return value}}
function toast(message,type='ok'){$('toast').textContent=message;$('toast').className=`show ${type}`;setTimeout(()=>$('toast').className='',2600)}
function openPage(page){const button=document.querySelector(`.nav[data-page="${page}"]`);if(!button)return;document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));button.classList.add('active');$(page).classList.add('active');$('page-heading').textContent=button.dataset.title;$('page-subtitle').textContent=button.dataset.subtitle;window.scrollTo({top:0,behavior:'smooth'});if(page==='dashboard'){loadDashboard();if(window.loadControlCenter)loadControlCenter()}if(page==='connections'&&window.loadIntegrations)loadIntegrations();if(page==='automation'&&window.loadOperations)loadOperations();if(page==='insights'&&window.loadInsights)loadInsights();if(page==='promotion'&&window.loadPromotion)loadPromotion()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));
document.querySelectorAll('.go-page').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.target)));
async function loadDashboard(){try{const d=await api('/api/command-center');$('dash-pending').textContent=d.task_counts.pending+d.task_counts.in_progress;$('dash-drafts').textContent=d.draft_count;$('dash-keywords').textContent=d.keyword_count;$('dash-calendar').textContent=d.calendar_days;$('dash-business-message').textContent=d.business_message;const verified=d.business_status==='verified';$('dash-data-badge').textContent=verified?'数据已验证':'等待数据接入';$('dash-data-badge').className=`status-pill ${verified?'ready':'waiting'}`;$('dash-recommendations').innerHTML=d.recommendations.map((x,i)=>`<div class="recommendation"><b>${i+1}</b><span>${esc(x)}</span></div>`).join('');$('dash-tasks').innerHTML=d.recent_tasks.length?d.recent_tasks.map(x=>`<div class="mini-row"><span class="dot ${esc(x.priority)}"></span><strong>${esc(x.title)}</strong><small>${esc(x.status_label)}</small></div>`).join(''):'<div class="friendly-empty">还没有任务，先安排一件今天要完成的事。</div>';$('dash-draft-list').innerHTML=d.recent_drafts.length?d.recent_drafts.map(x=>`<div class="mini-row"><span class="dot draft"></span><strong>${esc(x.kind)}</strong><small>${formatTime(x.created_at)}</small></div>`).join(''):'<div class="friendly-empty">还没有内容草稿，可从“内容增长”开始。</div>'}catch(e){toast(e.message,'error')}}
$('generate').addEventListener('click',async()=>{const b=$('generate');b.disabled=true;b.textContent='正在整理今天的数据…';try{const r=await api('/api/daily-review/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});showReview(r);await Promise.all([loadSummary(),loadPlan(),loadHistory(),loadMemory(),loadDashboard()]);toast('今日复盘已生成并保存')}catch(e){toast(e.message,'error')}finally{b.disabled=false;b.textContent='重新生成今日复盘'}});
$('today-label').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
(async()=>{try{const s=await api('/api/status');if(s.build!==BUILD)throw new Error('前后端构建版本不一致，请重新安装最新版本');document.querySelector('.service').classList.add('ok');$('service-text').textContent='本地服务正常';showReview(await api('/api/daily-review/latest'));await Promise.all([loadSummary(),loadPlan(),loadHistory(),loadMemory(),loadDashboard(),window.loadControlCenter?loadControlCenter():Promise.resolve()])}catch(e){$('service-text').textContent=e.message;toast(e.message,'error')}})();
console.log(`KAZUIZHI_BUILD=${BUILD}`);
