let operationsTasks=[];let taskFilter='all';
function renderTasks(){const items=operationsTasks.filter(x=>taskFilter==='all'||x.status===taskFilter);$('operations-tasks').className=items.length?'operations-list':'friendly-empty';$('operations-tasks').innerHTML=items.map((x,i)=>`<div class="operation-task"><span class="priority-bar ${esc(x.priority)}"></span><div><strong>${esc(x.title)}</strong><small>${esc(x.category)}${x.due_date?' · '+esc(x.due_date):''}</small></div><select data-task-index="${operationsTasks.indexOf(x)}"><option value="pending" ${x.status==='pending'?'selected':''}>待开始</option><option value="in_progress" ${x.status==='in_progress'?'selected':''}>进行中</option><option value="completed" ${x.status==='completed'?'selected':''}>已完成</option></select></div>`).join('')||'这个分类里还没有任务。';document.querySelectorAll('[data-task-index]').forEach(select=>select.addEventListener('change',async()=>{const item=operationsTasks[Number(select.dataset.taskIndex)];select.disabled=true;try{await api('/api/operations/tasks/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:select.value})});toast('任务状态已更新');await Promise.all([loadOperations(),loadDashboard()])}catch(e){toast(e.message,'error')}finally{select.disabled=false}}))}
function renderCalendar(data){$('promotion-calendar').className=data.items?.length?'calendar-list':'friendly-empty';$('promotion-calendar').innerHTML=data.items?.length?data.items.map((x,i)=>`<div class="calendar-day"><div><b>${esc(x.date.slice(5))}</b><small>周${esc(x.weekday)}</small></div><span><strong>${esc(x.theme)}</strong><small>${esc(x.action)}</small></span></div>`).join(''):'点击“生成日历”，获得一周待审核安排。'}
async function loadOperations(){try{const [tasks,calendar]=await Promise.all([api('/api/operations/tasks'),api('/api/operations/calendar')]);operationsTasks=tasks.items;renderTasks();renderCalendar(calendar)}catch(e){toast(e.message,'error')}}
window.loadOperations=loadOperations;
$('add-task').addEventListener('click',async()=>{const button=$('add-task');button.disabled=true;const original=button.textContent;button.textContent='加入中…';try{await api('/api/operations/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('task-title').value,priority:$('task-priority').value,due_date:$('task-date').value,category:'推广运营'})});$('task-title').value='';await Promise.all([loadOperations(),loadDashboard()]);toast('任务已加入清单')}catch(e){toast(e.message,'error')}finally{button.disabled=false;button.textContent=original}});
document.querySelectorAll('[data-task-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-task-filter]').forEach(x=>x.classList.remove('active'));button.classList.add('active');taskFilter=button.dataset.taskFilter;renderTasks();toast(`已切换到“${button.textContent.trim()}”任务`)}));
$('generate-calendar').addEventListener('click',async()=>{const button=$('generate-calendar');button.disabled=true;button.textContent='生成中…';try{const data=await api('/api/operations/calendar/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:$('calendar-region').value,service:$('calendar-service').value})});renderCalendar(data);await loadDashboard();toast('未来 7 天推广日历已生成')}catch(e){toast(e.message,'error')}finally{button.disabled=false;button.textContent='重新生成'}});
function renderDemand(data){const max=Math.max(1,...data.top_needs.map(x=>x.signals),...data.top_regions.map(x=>x.signals));const bars=(title,items)=>`<div class="insight-group"><h4>${title}</h4>${items.map(x=>`<div class="insight-bar"><span>${esc(x.name)}</span><i><b style="width:${Math.max(8,x.signals/max*100)}%"></b></i><em>${x.signals} 条</em></div>`).join('')}</div>`;$('demand-insights').className='demand-panel';$('demand-insights').innerHTML=`<div class="signal-summary"><strong>${data.public_signal_count}</strong><span>条公开研究信号</span></div>${bars('关注服务',data.top_needs)}${bars('关注区域',data.top_regions)}<div class="truth-box"><b>${esc(data.business_data_status)}</b><br>${esc(data.insight)}</div>`}
function renderCompetition(data){$('competition-title').textContent=data.headline;$('competition-output').className='competition-report';$('competition-output').innerHTML=`<div class="report-summary"><span>基于 ${data.evidence_count} 条观察</span><b>待人工审核</b></div><div class="report-columns"><div><h4>观察记录</h4>${data.observations.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div><div><h4>建议机会</h4>${data.opportunities.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div></div><div class="truth-box">${esc(data.limitations)}</div>`}
async function loadInsights(){try{renderDemand(await api('/api/insights/demand'))}catch(e){toast(e.message,'error')}}
window.loadInsights=loadInsights;
$('refresh-demand').addEventListener('click',async()=>{const button=$('refresh-demand');button.disabled=true;const original=button.textContent;button.textContent='刷新中…';try{await loadInsights();toast('客户需求信号已刷新')}finally{button.disabled=false;button.textContent=original}});
$('generate-competition').addEventListener('click',async()=>{const button=$('generate-competition');button.disabled=true;button.textContent='正在分析…';try{const data=await api('/api/insights/competition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:$('comp-region').value,category:$('comp-category').value,observations:$('comp-observations').value})});renderCompetition(data);toast('竞争观察报告已保存')}catch(e){toast(e.message,'error')}finally{button.disabled=false;button.textContent='生成竞争观察报告'}});
loadOperations();loadInsights();
