(() => {
  const byId=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  async function json(path, options){const response=await fetch(path,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`本地搜索服务返回 ${response.status}`);return data}
  function campaignOptions(){const select=byId('search-campaign');if(!select)return;const selected=select.value;select.innerHTML='<option value="">选择增长战役</option>'+(window.state?.factory?.campaigns||[]).map(item=>`<option value="${esc(item.id)}">${esc(item.region)} · ${esc(item.service)} · ${esc(item.title)}</option>`).join('');select.value=selected}
  function render(data){const audit=data.latest_audit,box=byId('search-status');if(box)box.innerHTML=audit?`<div class="check-item"><div><b>官网首页 ${audit.homepage_status}</b><small>robots.txt ${audit.robots_status} · sitemap.xml ${audit.sitemap_status} · 结构化数据 ${audit.has_structured_data?'有':'无'}</small></div><strong class="${audit.result==='ready'?'pass':'wait'}">${audit.result==='ready'?'技术底座通过':'需要处理'}</strong></div>${(audit.blockers||[]).map(item=>`<div class="search-blocker">${esc(item)}</div>`).join('')}`:'<p>尚未运行官网抓取检查。</p>';const packs=byId('search-pack-list');if(packs)packs.innerHTML=(data.packs||[]).length?data.packs.map(item=>`<div class="card-row"><div><b>${esc(item.page_title)}</b><span>${esc(item.id)} · ${esc(item.deployment_status)} · ${esc(item.indexing_status)}</span></div><em class="status">内容包</em></div>`).join(''):'<div class="empty">还没有本地搜索内容包。先建立增长战役，再生成同源网页、FAQ和AI短答案。</div>'}
  async function load(){campaignOptions();const data=await json('/api/search-growth',{cache:'no-store'});if(window.state)window.state.search=data;render(data);window.dispatchEvent(new Event('operational:search-updated'));return data}
  byId('search-audit')?.addEventListener('click',async event=>{event.currentTarget.disabled=true;try{const result=await json('/api/search-growth/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site:'https://kazuizhi.com/'})});await load();window.notify?.(result.result==='ready'?'官网技术底座检查通过':`发现 ${result.blockers.length} 个搜索技术堵点`)}catch(error){window.notify?.(error.message,'error')}finally{event.currentTarget.disabled=false}});
  byId('search-pack')?.addEventListener('click',async event=>{const campaignId=byId('search-campaign')?.value;if(!campaignId)return window.notify?.('请先选择增长战役','error');event.currentTarget.disabled=true;try{await json('/api/search-growth/packs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:campaignId})});await load();window.notify?.('SEO网页、FAQ与GEO短答案已生成并绑定增长ID')}catch(error){window.notify?.(error.message,'error')}finally{event.currentTarget.disabled=false}});
  window.searchGrowthActivate=load;
})();
