document.body.classList.toggle('embedded',new URLSearchParams(location.search).get('embedded')==='1');
const $=id=>document.getElementById(id);
const state={factory:null};
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function api(path,options){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`本地服务返回 ${response.status}`);return data}
function notify(message,type='ok'){const el=$('feedback');el.textContent=type==='error'?`需要处理：${message}`:`操作结果：${message}`;el.className=`feedback${type==='error'?' error':''}`;el.hidden=false;window.setTimeout(()=>el.hidden=true,3600)}
function statusText(status){return status||'待配置'}
function changePage(page){const nav=document.querySelector(`.nav[data-page="${page}"]`);if(!nav)return;document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$(page).classList.add('active');$('crumb').textContent=nav.parentElement?.previousElementSibling?.textContent||'卡嘴子 AI';$('page-title').textContent=nav.textContent;loadPage(page).catch(error=>notify(error.message,'error'))}
async function loadFactory(){state.factory=await api('/api/content-factory');return state.factory}
function campaignOptions(selected=''){const campaigns=state.factory?.campaigns||[];return `<option value="">请选择增长战役</option>${campaigns.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.id)} · ${esc(x.title)}</option>`).join('')}`}
function renderCampaigns(){const items=state.factory?.campaigns||[];$('campaign-list').innerHTML=items.length?items.map(x=>`<div class="card-row"><div><b>${esc(x.title)}</b><span>${esc(x.id)} · ${esc(x.region)} · ${esc(x.service)} · ${esc(x.goal)}</span></div><em class="status">${esc(statusText(x.status))}</em></div>`).join(''):'<div class="empty">还没有增长战役。先从一个真实用户问题开始。</div>';const select=$('video-campaign');if(select)select.innerHTML=campaignOptions(select.value)}
function renderVideos(){const items=state.factory?.videos||[];const review=items.filter(x=>x.status==='等待人工审核');$('review-count').textContent=`${review.length} 条`;const card=item=>`<div class="review-row"><b>${esc(item.script.slice(0,34))}${item.script.length>34?'…':''}</b><span>${esc(item.id)} · ${esc(item.status)} · 候选 ${item.candidates?.length||0} 个</span>${['等待生产','生产中','退回修改'].includes(item.status)?`<div class="video-actions"><button class="approve" data-render-video="${esc(item.id)}">3060 生成成片</button></div>`:''}${item.status==='等待人工审核'?`<div class="video-actions"><button class="approve" data-approve="${esc(item.id)}">确认发布</button><button data-return="${esc(item.id)}">退回修改</button></div>`:''}</div>`;$('review-list').innerHTML=review.length?review.map(card).join(''):'<div class="empty">没有待审核视频。完成生产后会集中显示在这里。</div>';$('video-list').innerHTML=items.length?items.map(card).join(''):'<div class="empty">还没有视频任务。请先建立战役、登记素材，再创建生产任务。</div>';document.querySelectorAll('[data-approve]').forEach(button=>button.addEventListener('click',()=>reviewVideo(button.dataset.approve,'确认发布')));document.querySelectorAll('[data-return]').forEach(button=>button.addEventListener('click',()=>reviewVideo(button.dataset.return,'退回修改')))}
function renderAccounts(){const items=state.factory?.accounts||[];$('account-list').innerHTML=items.length?items.map(x=>`<div class="card-row"><div><b>${esc(x.platform)} · ${esc(x.account_name)}</b><span>${esc(x.region||'未绑定区域')} · ${esc(x.service||'未设置服务主线')} · 每日上限 ${esc(x.daily_limit||1)} 条</span></div><em class="status">${esc(x.connection_status)}</em></div>`).join(''):'<div class="empty">暂未建立账号档案。首次登录授权后，系统才允许进入发布排期。</div>'}
function renderDashboard(){const f=state.factory||{};const stateCount=f.video_states||{};const waiting=stateCount['等待人工审核']||0;const publishing=stateCount['等待最佳时间']||0;const verified=f.verified_publications||0;$('today-tasks').innerHTML=`<div class="task-row"><b>收集本地需求与服务问题</b><span>由市场信号、客服问题和历史内容共同驱动</span></div><div class="task-row"><b>生成并质检视频候选</b><span>当前等待人工审核 ${waiting} 条</span></div><div class="task-row"><b>已审核内容进入账号排期</b><span>当前等待最佳时间 ${publishing} 条</span></div><div class="task-row"><b>回收真实发布与订单结果</b><span>已验证发布 ${verified} 条</span></div>`;const labels=[['真实发布',verified],['有效咨询','--'],['小程序需求','--'],['师傅报价','--'],['完成订单','--'],['待处理阻塞',waiting]];$('funnel').innerHTML=labels.map(([name,value])=>`<div class="metric"><span>${name}</span><b>${value}</b><small>${name==='真实发布'?'均需平台内容链接':'等待已验证经营数据'}</small></div>`).join('');$('order-goal').textContent=`-- / 50`; $('goal-progress').style.width='0%'}
function renderHealth(){const f=state.factory||{},device=state.device||{},worker=state.worker||{},search=state.search||{},verifiedAccounts=(f.accounts||[]).filter(x=>x.connection_status==='已验证可发布').length;const rows=[['数据与历史迁移','通过','覆盖升级前复制原任务、运营记忆、经营数据、连接、设备与账号资料'],['内容工厂真实门槛','通过','增长ID、素材、视频、审核、排期和真实发布回执分离保存'],['手机与真机执行',device.status==='online'?'通过':'待现场检查',device.status==='online'?`${device.devices?.length||1} 台设备在线；有效PNG才替换画面`:'当前未检测到手机在线；插入USB后完成画面、点击、滑动验收'],['3060视频工厂',worker.status==='ready'?'通过':'待配置',worker.status==='ready'?`${worker.gpu?.description||'RTX GPU'} · NVENC硬件编码`:'视频组件或GPU尚未完全通过'],['社媒账号授权',verifiedAccounts?'通过':'待人工登录',verifiedAccounts?`${verifiedAccounts} 个账号已验证可发布`:'验证码、人脸或平台风控必须由账号本人处理'],['小程序与订单归因','待验证','需要接入内容ID、团长码与真实经营数据'],['SEO与GEO技术底座',search.latest_audit?.result==='ready'?'通过':'待部署',search.latest_audit?`官网堵点 ${search.latest_audit.blockers?.length||0} 项；收录仍以真实观察为准`:'尚未运行官网robots、sitemap与结构化数据检查']];$('health-list').innerHTML=rows.map(([title,status,detail])=>`<div class="check-item"><div><b>${title}</b><small>${detail}</small></div><strong class="${status==='通过'?'pass':'wait'}">${status}</strong></div>`).join('')}
async function reviewVideo(videoId,decision){const video=(state.factory?.videos||[]).find(x=>x.id===videoId);const candidate=video?.candidates?.find(x=>x.exists);if(decision==='确认发布'&&!candidate){notify('当前没有真实存在的成片文件，不能确认发布','error');return}try{await api('/api/content-factory/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_id:videoId,decision,candidate_id:candidate?.id||'',note:''})});await refreshAll();notify(decision==='确认发布'?'视频已授权，将等待账号与最佳发布时间':'视频已退回生产队列')}catch(error){notify(error.message,'error')}}
async function loadSystemHealth(){const results=await Promise.allSettled([api('/api/video-worker'),api('/api/search-growth'),api('/api/r8/device/status')]);state.worker=results[0].status==='fulfilled'?results[0].value:null;state.search=results[1].status==='fulfilled'?results[1].value:null;state.device=results[2].status==='fulfilled'?results[2].value:null}
async function refreshAll(){await Promise.all([loadFactory(),loadSystemHealth()]);renderDashboard();renderCampaigns();renderVideos();renderAccounts();renderHealth()}
async function loadPage(page){if(!state.factory)await loadFactory();if(page==='dashboard')renderDashboard();if(page==='campaigns')renderCampaigns();if(page==='content'){renderCampaigns();renderVideos()}if(page==='accounts')renderAccounts();if(page==='health')renderHealth();if(page==='device')window.deviceCenterActivate?.();if(page==='search')window.searchGrowthActivate?.()}
window.state=state;window.refreshAll=refreshAll;window.notify=notify;
document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>changePage(button.dataset.page)));document.querySelectorAll('[data-page-target]').forEach(button=>button.addEventListener('click',()=>changePage(button.dataset.pageTarget)));
$('campaign-form').addEventListener('submit',async event=>{event.preventDefault();try{const item=await api('/api/content-factory/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:$('campaign-region').value,service:$('campaign-service').value,title:$('campaign-title').value,evidence:$('campaign-evidence').value,goal:$('campaign-goal').value})});await refreshAll();$('video-campaign').value=item.id;changePage('content');notify(`已建立增长ID：${item.id}`)}catch(error){notify(error.message,'error')}});
$('create-video').addEventListener('click',async()=>{try{await api('/api/content-factory/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:$('video-campaign').value,script:$('video-script').value,cta:$('video-cta').value})});await refreshAll();notify('视频生产任务已建立；需要先登记真实素材后才能进入实际生产')}catch(error){notify(error.message,'error')}});
$('account-form').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/content-factory/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform:$('account-platform').value,account_name:$('account-name').value,region:$('account-region').value,service:$('account-service').value,connection_status:$('account-status').value})});await refreshAll();notify('账号档案已保存；真实发布能力以现场授权检测为准')}catch(error){notify(error.message,'error')}});
$('refresh-campaigns').addEventListener('click',()=>refreshAll().catch(error=>notify(error.message,'error')));$('refresh-accounts').addEventListener('click',()=>refreshAll().catch(error=>notify(error.message,'error')));
setInterval(()=>$('clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()),1000);$('clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date());
refreshAll().catch(error=>notify(error.message,'error'));
