document.body.classList.toggle('embedded',new URLSearchParams(location.search).get('embedded')==='1');
const $=id=>document.getElementById(id);
const state={factory:null,device:null,worker:null,search:null,currentPage:'dashboard'};
function loadProductizationAssets(){if(!document.querySelector('link[data-v221-productization]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/operational-productization.css';link.dataset.v221Productization='1';document.head.appendChild(link)}if(!document.querySelector('script[data-v221-productization]')){const script=document.createElement('script');script.src='/operational-productization.js';script.defer=true;script.dataset.v221Productization='1';document.head.appendChild(script)}}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function api(path,options){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`本地服务返回 ${response.status}`);return data}
function notify(message,type='ok'){const el=$('feedback');el.textContent=type==='error'?`需要处理：${message}`:`操作结果：${message}`;el.className=`feedback${type==='error'?' error':''}`;el.hidden=false;window.setTimeout(()=>el.hidden=true,4200)}
function statusText(status){return status||'待配置'}
function deviceSnapshot(payload=state.device||{}){const devices=Array.isArray(payload.devices)?payload.devices:[];const connected=devices.filter(x=>x&&x.connected);const primary=connected.find(x=>x.device_id===payload.primary_device_id)||connected[0]||null;return{online:Boolean(primary),primary,count:connected.length,adb:payload.adb||{},message:payload.message||''}}
function syncOperationalDeviceStatus(payload){if(payload&&typeof payload==='object')state.device=payload;if(state.currentPage==='health')renderHealth();window.dispatchEvent(new CustomEvent('operational:device-status',{detail:payload||null}))}
function changePage(page){const nav=document.querySelector(`.nav[data-page="${page}"]`);if(!nav)return;const previous=state.currentPage;if(previous==='device'&&page!=='device')window.deviceCenterDeactivate?.();document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$(page).classList.add('active');state.currentPage=page;$('crumb').textContent=nav.parentElement?.previousElementSibling?.textContent||'卡嘴子 AI';$('page-title').textContent=nav.textContent;loadPage(page).catch(error=>notify(error.message,'error'))}
async function loadFactory(){state.factory=await api('/api/content-factory');return state.factory}
function campaignOptions(selected=''){const campaigns=state.factory?.campaigns||[];return `<option value="">请选择增长战役</option>${campaigns.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.id)} · ${esc(x.title)}</option>`).join('')}`}
function renderCampaigns(){const items=state.factory?.campaigns||[];$('campaign-list').innerHTML=items.length?items.map(x=>`<div class="card-row"><div><b>${esc(x.title)}</b><span>${esc(x.id)} · ${esc(x.region)} · ${esc(x.service)} · ${esc(x.goal)}</span></div><em class="status">${esc(statusText(x.status))}</em></div>`).join(''):'<div class="empty">还没有增长战役。先从一个真实用户问题开始。</div>';const select=$('video-campaign');if(select)select.innerHTML=campaignOptions(select.value)}
function videoTitle(item){const titles=item.production_plan?.titles||[];return titles[0]||item.production_plan?.topic||item.script||item.id}
function candidateVideo(item){const candidate=(item.candidates||[]).find(x=>x.exists);if(!candidate)return'';const src=`/api/content-factory/candidate-file?video_id=${encodeURIComponent(item.id)}&candidate_id=${encodeURIComponent(candidate.id)}`;return `<div class="factory-video-preview"><video controls preload="metadata" playsinline src="${src}"></video><small>FINAL.MP4 · ${esc(candidate.duration_seconds||'--')} 秒 · 技术质检 ${candidate.technical_qc?.passed?'通过':'待确认'}</small></div>`}
function workflowDetail(item){const pieces=[];if(item.bottleneck)pieces.push(`<div class="factory-bottleneck"><b>当前卡点</b><span>${esc(item.bottleneck)}</span></div>`);if(item.auto_action)pieces.push(`<div class="factory-auto-action"><b>系统处理</b><span>${esc(item.auto_action)}</span></div>`);if(item.last_error)pieces.push(`<details><summary>最近一次错误</summary><small>${esc(item.last_error)}</small></details>`);return pieces.join('')}
function videoCard(item){const review=item.status==='等待人工审核';const hold=item.status==='已暂缓';const plan=item.production_plan;const title=videoTitle(item);const planLine=plan?`ChatGPT生产合同 V${esc(item.plan_version||1)} · ${esc((item.target_platforms||[]).join(' / ')||'通用')}`:'等待 ChatGPT 总控制返回生产方案';return `<div class="review-row factory-video-card"><div><b>${esc(String(title).slice(0,56))}${String(title).length>56?'…':''}</b><span>${esc(item.id)} · ${esc(item.status)} · ${planLine}</span></div>${candidateVideo(item)}${workflowDetail(item)}${review?`<div class="video-actions"><button class="approve" data-approve="${esc(item.id)}">通过并发布</button><button data-return="${esc(item.id)}">退回重做</button><button data-hold="${esc(item.id)}">暂不发布</button></div>`:''}${hold?'<small>这条成片已保留，不会自动发布。后续可重新进入审核。</small>':''}</div>`}
function bindVideoActions(){document.querySelectorAll('[data-approve]').forEach(button=>button.addEventListener('click',()=>reviewVideo(button.dataset.approve,'确认发布')));document.querySelectorAll('[data-return]').forEach(button=>button.addEventListener('click',()=>reviewVideo(button.dataset.return,'退回重做')));document.querySelectorAll('[data-hold]').forEach(button=>button.addEventListener('click',()=>reviewVideo(button.dataset.hold,'暂不发布')))}
function renderVideos(){const items=state.factory?.videos||[];const review=items.filter(x=>x.status==='等待人工审核');$('review-count').textContent=`${review.length} 条`;$('review-list').innerHTML=review.length?review.map(videoCard).join(''):'<div class="empty">没有待审核视频。ChatGPT与本地生产线完成后会自动集中到这里。</div>';$('video-list').innerHTML=items.length?items.map(videoCard).join(''):'<div class="empty">还没有视频任务。选择增长战役后点击“开始 AI 自动生产”；本地素材不是前置条件。</div>';bindVideoActions()}
function renderAccounts(){const items=state.factory?.accounts||[];$('account-list').innerHTML=items.length?items.map(x=>`<div class="card-row"><div><b>${esc(x.platform)} · ${esc(x.account_name)}</b><span>${esc(x.region||'未绑定区域')} · ${esc(x.service||'未设置服务主线')} · 每日上限 ${esc(x.daily_limit||1)} 条</span></div><em class="status">${esc(x.connection_status)}</em></div>`).join(''):'<div class="empty">暂未建立账号档案。首次登录授权后，系统才允许进入发布排期。</div>'}
function renderDashboard(){const f=state.factory||{};const stateCount=f.video_states||{};const waiting=stateCount['等待人工审核']||0;const planning=(stateCount['等待ChatGPT策划']||0)+(stateCount['退回重做']||0);const producing=(stateCount['等待生产']||0)+(stateCount['生产中']||0)+(stateCount['技术质检']||0);const publishing=stateCount['等待最佳时间']||0;const errors=stateCount['异常待处理']||0;const verified=f.verified_publications||0;$('today-tasks').innerHTML=`<div class="task-row"><b>ChatGPT 总控制策划</b><span>等待策划/重做 ${planning} 条</span></div><div class="task-row"><b>RTX3060 与本地执行</b><span>队列/生产/质检 ${producing} 条</span></div><div class="task-row"><b>老板只看最终成片</b><span>当前待审核 ${waiting} 条</span></div><div class="task-row"><b>审核后进入平台执行</b><span>等待最佳时间 ${publishing} 条 · 异常 ${errors} 条</span></div>`;const labels=[['真实发布',verified],['待审核成片',waiting],['自动生产',producing],['ChatGPT策划',planning],['发布排期',publishing],['需处理异常',errors]];$('funnel').innerHTML=labels.map(([name,value])=>`<div class="metric"><span>${name}</span><b>${value}</b><small>${name==='真实发布'?'均需平台内容链接':'来自真实任务状态'}</small></div>`).join('');$('order-goal').textContent=`-- / 50`; $('goal-progress').style.width='0%'}
function renderHealth(){const f=state.factory||{},worker=state.worker||{},search=state.search||{},device=deviceSnapshot(),verifiedAccounts=(f.accounts||[]).filter(x=>x.connection_status==='已验证可发布').length;const deviceDetail=device.online?`${device.count} 台设备在线${device.primary?.model?` · ${device.primary.model}`:''}${device.primary?.android_version?` · Android ${device.primary.android_version}`:''}`:(device.message||'当前未检测到手机在线；插入USB后完成画面、点击、滑动验收');const rows=[['数据与历史迁移','通过','覆盖升级前复制原任务、运营记忆、经营数据、连接、设备与账号资料'],['ChatGPT内容生产合同','通过','增长ID→ChatGPT结构化分镜/EDL→本地执行；本地素材为可选增强'],['手机与真机执行',device.online?'通过':'待现场检查',deviceDetail],['3060视频工厂',worker.ffmpeg_found?'通过':'待配置',worker.ffmpeg_found?`${worker.gpu?.description||'兼容编码'} · 队列 ${worker.queue_depth||0} 条`:'视频组件尚未完全通过'],['社媒账号授权',verifiedAccounts?'通过':'待人工登录',verifiedAccounts?`${verifiedAccounts} 个账号已验证可发布`:'验证码、人脸或平台风控必须由账号本人处理'],['小程序与订单归因','待验证','需要接入内容ID、团长码与真实经营数据'],['SEO与GEO技术底座',search.latest_audit?.result==='ready'?'通过':'待部署',search.latest_audit?`官网堵点 ${search.latest_audit.blockers?.length||0} 项；收录仍以真实观察为准`:'尚未运行官网robots、sitemap与结构化数据检查']];$('health-list').innerHTML=rows.map(([title,status,detail])=>`<div class="check-item"><div><b>${title}</b><small>${detail}</small></div><strong class="${status==='通过'?'pass':'wait'}">${status}</strong></div>`).join('')}
async function reviewVideo(videoId,decision){const video=(state.factory?.videos||[]).find(x=>x.id===videoId);const candidate=video?.candidates?.find(x=>x.exists);if(decision==='确认发布'&&!candidate){notify('当前没有真实存在的 FINAL.MP4，不能确认发布','error');return}try{await api('/api/content-factory/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_id:videoId,decision,candidate_id:candidate?.id||'',note:''})});await refreshAll();notify(decision==='确认发布'?'已通过；将进入平台规则检查与发布编排':decision==='暂不发布'?'已暂缓；不会自动发布':'已退回；ChatGPT会重新判断并生成新版本')}catch(error){notify(error.message,'error')}}
async function loadSystemHealth(){const results=await Promise.allSettled([api('/api/video-worker'),api('/api/search-growth'),api('/api/r8/device/status')]);if(results[0].status==='fulfilled')state.worker=results[0].value;if(results[1].status==='fulfilled')state.search=results[1].value;if(results[2].status==='fulfilled')state.device=results[2].value}
async function refreshAll(){await Promise.all([loadFactory(),loadSystemHealth()]);renderDashboard();renderCampaigns();renderVideos();renderAccounts();renderHealth();window.dispatchEvent(new Event('operational:refreshed'))}
async function loadPage(page){if(!state.factory)await loadFactory();if(page==='dashboard')renderDashboard();if(page==='campaigns')renderCampaigns();if(page==='content'){renderCampaigns();renderVideos()}if(page==='accounts')renderAccounts();if(page==='health'){await loadSystemHealth();renderHealth();window.dispatchEvent(new Event('operational:refreshed'))}if(page==='device')window.deviceCenterActivate?.();if(page==='search')window.searchGrowthActivate?.()}
window.state=state;window.refreshAll=refreshAll;window.notify=notify;window.syncOperationalDeviceStatus=syncOperationalDeviceStatus;window.changeOperationalPage=changePage;
document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>changePage(button.dataset.page)));document.querySelectorAll('[data-page-target]').forEach(button=>button.addEventListener('click',()=>changePage(button.dataset.pageTarget)));
$('campaign-form').addEventListener('submit',async event=>{event.preventDefault();try{const item=await api('/api/content-factory/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:$('campaign-region').value,service:$('campaign-service').value,title:$('campaign-title').value,evidence:$('campaign-evidence').value,goal:$('campaign-goal').value})});await refreshAll();$('video-campaign').value=item.id;changePage('content');notify(`已建立增长ID：${item.id}；可直接开始AI生产`)}catch(error){notify(error.message,'error')}});
$('create-video').addEventListener('click',async()=>{try{const campaignId=$('video-campaign').value;if(!campaignId)throw new Error('请先选择增长战役');await api('/api/content-factory/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:campaignId,cta:$('video-cta')?.value||'通过小程序提交需求，等待师傅报价'})});await refreshAll();notify('生产请求已提交：ChatGPT负责策划，本地素材有就用、没有也不会阻塞')}catch(error){notify(error.message,'error')}});
$('account-form').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/content-factory/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform:$('account-platform').value,account_name:$('account-name').value,region:$('account-region').value,service:$('account-service').value,connection_status:$('account-status').value})});await refreshAll();notify('账号档案已保存；真实发布能力以现场授权检测为准')}catch(error){notify(error.message,'error')}});
$('refresh-campaigns').addEventListener('click',()=>refreshAll().catch(error=>notify(error.message,'error')));$('refresh-accounts').addEventListener('click',()=>refreshAll().catch(error=>notify(error.message,'error')));
setInterval(()=>$('clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()),1000);$('clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date());
loadProductizationAssets();
refreshAll().catch(error=>notify(error.message,'error'));