let keywordData=[];let promotionRecords=[];let lastPromotionText='';
const SOURCE_LABELS={historical_public_signal:'公开研究词',owner_input:'手动添加',product_strategy_seed:'产品方向词'};
const FIELD_LABELS={title:'标题',meta_description:'页面简介',outline:'内容提纲',draft:'正文草稿',review_notes:'发布前检查',landing_page:'本地页面方案',local_profile:'本地资料检查',faq:'常见问题',measurement:'效果记录方法',audience:'目标用户',evidence_used:'使用的证据',positioning:'品牌表达',variants:'文案方案',safety_check:'安全检查',duration:'建议时长',hook:'开场',shots:'分镜脚本',caption:'配文',cta:'行动提示'};
function promotionPayload(){return{region:$('promo-region').value.trim(),service:$('promo-service').value.trim(),keyword:$('promo-keyword').value.trim(),audience:$('promo-audience').value.trim(),evidence:$('promo-evidence').value.trim()}}
function renderValue(value){if(Array.isArray(value))return`<div class="result-list">${value.map((item,i)=>typeof item==='object'?`<div class="result-step"><b>${i+1}</b><div>${renderValue(item)}</div></div>`:`<div class="result-step"><b>${i+1}</b><span>${esc(item)}</span></div>`).join('')}</div>`;if(value&&typeof value==='object')return Object.entries(value).map(([key,item])=>`<div class="result-field"><strong>${esc(FIELD_LABELS[key]||key)}</strong>${renderValue(item)}</div>`).join('');return`<p>${esc(value)}</p>`}
function showPromotion(record){$('promotion-output-title').textContent=record.kind+'（待人工审核）';$('promotion-output').className='promotion-output';$('promotion-output').innerHTML=renderValue(record.output);lastPromotionText=Object.entries(record.output).map(([k,v])=>`${FIELD_LABELS[k]||k}\n${typeof v==='string'?v:JSON.stringify(v,null,2)}`).join('\n\n');$('copy-promotion').disabled=false}
function filterKeywords(){const query=$('keyword-search').value.trim().toLowerCase();const source=$('keyword-source').value;const items=keywordData.filter(x=>(source==='all'||x.source===source)&&(!query||x.keyword.toLowerCase().includes(query)||String(x.region||'').includes(query)||String(x.category||'').includes(query)));$('keyword-count').textContent=`${items.length} 条`;$('keyword-list').className=items.length?'keyword-list':'friendly-empty';$('keyword-list').innerHTML=items.map(x=>`<button class="keyword-item" data-index="${keywordData.indexOf(x)}"><span><strong>${esc(x.keyword)}</strong><small>${esc([x.region,x.category].filter(Boolean).join(' · ')||'点击即可使用')}</small></span><em>${esc(SOURCE_LABELS[x.source]||'研究词')}</em></button>`).join('')||'没有找到匹配关键词，换个词试试。';document.querySelectorAll('.keyword-item').forEach(button=>button.addEventListener('click',()=>{const item=keywordData[Number(button.dataset.index)];$('promo-keyword').value=item.keyword;if(item.region&&!$('promo-region').value)$('promo-region').value=item.region;if(item.category&&!$('promo-service').value)$('promo-service').value=item.category;document.querySelectorAll('.keyword-item').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');toast('关键词已填入右侧')}))}
async function loadPromotion(){const [keywords,history]=await Promise.all([api('/api/promotion/keywords'),api('/api/promotion/history')]);keywordData=keywords.items;promotionRecords=history.items;filterKeywords();$('promotion-history').className=promotionRecords.length?'history-list':'';$('promotion-history').innerHTML=promotionRecords.slice(0,8).map((x,i)=>`<button class="history-item" data-record="${i}"><span class="history-icon">${esc(x.kind.slice(0,1))}</span><span><strong>${esc(x.kind)}</strong><small>${formatTime(x.created_at)} · 待人工审核</small></span><b>查看</b></button>`).join('')||'<div class="friendly-empty">还没有草稿，生成第一份后会显示在这里。</div>';document.querySelectorAll('.history-item').forEach(button=>button.addEventListener('click',()=>{showPromotion(promotionRecords[Number(button.dataset.record)]);$('promotion-output').scrollIntoView({behavior:'smooth',block:'center'})}))}
window.loadPromotion=loadPromotion;
$('keyword-search').addEventListener('input',filterKeywords);$('keyword-source').addEventListener('change',filterKeywords);
$('save-keyword').addEventListener('click',async()=>{try{await api('/api/promotion/keywords',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({keyword:$('keyword-add').value,region:$('keyword-region').value})});$('keyword-add').value='';await loadPromotion();toast('关键词已保存')}catch(e){toast(e.message,'error')}});
$('clear-promotion').addEventListener('click',()=>{['promo-region','promo-service','promo-keyword','promo-audience','promo-evidence'].forEach(id=>$(id).value='');document.querySelectorAll('.keyword-item').forEach(x=>x.classList.remove('selected'));toast('内容输入已清空')});
$('copy-promotion').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(lastPromotionText);toast('结果已复制，可粘贴到其他地方')}catch{toast('复制失败，请手动选择内容','error')}});
document.querySelectorAll('[data-generator]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;const original=button.innerHTML;button.textContent='正在生成…';try{const record=await api('/api/promotion/'+button.dataset.generator,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(promotionPayload())});showPromotion(record);await loadPromotion();toast('草稿已生成并保存在本机')}catch(e){toast(e.message,'error')}finally{button.disabled=false;button.innerHTML=original}}));
loadPromotion().catch(e=>toast(e.message,'error'));
