Write-Host "Building Kazuizhi AI V1.9.5 Enterprise Installer"

$root = Resolve-Path "$PSScriptRoot\..\.."
$output = Join-Path $root "installer_output"

# Clean old installer output to prevent stale package reuse
if (Test-Path $output) {
    Remove-Item $output -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $output | Out-Null

Set-Location $PSScriptRoot

$iss = Get-ChildItem -Path $PSScriptRoot -Filter "*.iss" | Select-Object -First 1

if ($null -eq $iss) {
    throw "No Inno Setup script found"
}

Write-Host "Using installer script: $($iss.FullName)"

if (Get-Command iscc -ErrorAction SilentlyContinue) {
    iscc $iss.FullName
} else {
    throw "Missing Inno Setup compiler"
}

# Detect installer generated by Inno Setup directly from installer_output
$setup = Get-ChildItem -Path $output -Filter "*Setup.exe" | Select-Object -First 1

if ($null -eq $setup) {
    Write-Host "Installer output directory contents:"
    Get-ChildItem $output -Recurse
    throw "Installer exe was not generated in installer_output"
}

Write-Host "Installer generated: $($setup.FullName)"

Get-ChildItem $output

Write-Host "Installer output created"
